@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CustomerManager
participant EditJobOpeningUI <<presentation>>
participant EditJobOpeningController <<application>>
participant JobOpeningRepository <<repository>>
participant ClientRepository <<repository>>
participant JobOpening <<domain>>

activate CustomerManager
CustomerManager -> EditJobOpeningUI : asks to edit a job opening
activate EditJobOpeningUI
EditJobOpeningUI -> EditJobOpeningController : listInactiveJobOpenings()
activate EditJobOpeningController
EditJobOpeningController -> JobOpeningRepository : findAllInactiveJobOpenings()
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : List<JobOpening>
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : List<JobOpening>
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : shows list of inactive job openings\nand asks to select one
CustomerManager -> EditJobOpeningUI : selects one job opening
EditJobOpeningUI --> CustomerManager : shows list of attributes to\nedit and asks to select one
CustomerManager -> EditJobOpeningUI : selects client attribute
EditJobOpeningUI -> EditJobOpeningController : listClients()
activate EditJobOpeningController
EditJobOpeningController -> ClientRepository : findAll()
activate ClientRepository
ClientRepository --> EditJobOpeningController : List<Client>
deactivate ClientRepository
EditJobOpeningController --> EditJobOpeningUI : List<Client>
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : shows list of clients and\nasks to select new one
CustomerManager -> EditJobOpeningUI : selects new client
EditJobOpeningUI -> EditJobOpeningController : editClient(JobOpening jobOpening, Client client)
activate EditJobOpeningController
EditJobOpeningController -> JobOpening : editClient(Client client)
EditJobOpeningController -> JobOpeningRepository : save(JobOpening jobOpening)
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : jobOpening
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : jobOpening
EditJobOpeningUI --> CustomerManager : backs to menu
deactivate EditJobOpeningUI

@enduml