@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CustomerManager
participant EditJobOpeningUI <<presentation>>
participant EditJobOpeningController <<application>>
participant JobOpeningRepository <<repository>>
participant JobOpening <<domain>>

activate CustomerManager
CustomerManager -> EditJobOpeningUI : asks to edit a job opening
activate EditJobOpeningUI
EditJobOpeningUI -> EditJobOpeningController : listInactiveJobOpenings()
activate EditJobOpeningController
EditJobOpeningController -> JobOpeningRepository : findAllInactiveJobOpenings()
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : List<JobOpening>
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : List<JobOpening>
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : shows list of inactive job openings\nand asks to select one
CustomerManager -> EditJobOpeningUI : selects one job opening
EditJobOpeningUI --> CustomerManager : shows list of attributes to\nedit and asks to select one
CustomerManager -> EditJobOpeningUI : selects working mode attribute
EditJobOpeningUI --> CustomerManager : shows list of working mode\nand asks to select new one
CustomerManager -> EditJobOpeningUI : selects new working mode
EditJobOpeningUI -> EditJobOpeningController : editWorkingMode(JobOpening jobOpening, WorkingMode workingMode)
activate EditJobOpeningController
EditJobOpeningController -> JobOpening : editNumberVacancies(WorkingMode workingMode)
EditJobOpeningController -> JobOpeningRepository : save(JobOpening jobOpening)
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : jobOpening
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : jobOpening
EditJobOpeningUI --> CustomerManager : backs to menu
deactivate EditJobOpeningUI

@enduml