@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CustomerManager
participant EditJobOpeningUI <<presentation>>
participant EditJobOpeningController <<application>>
participant JobOpeningRepository <<repository>>
participant JobOpening <<domain>>

activate CustomerManager
CustomerManager -> EditJobOpeningUI : asks to edit a job opening
activate EditJobOpeningUI
EditJobOpeningUI -> EditJobOpeningController : listInactiveJobOpenings()
activate EditJobOpeningController
EditJobOpeningController -> JobOpeningRepository : findAllInactiveJobOpenings()
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : List<JobOpening>
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : List<JobOpening>
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : shows list of inactive job openings\nand asks to select one
CustomerManager -> EditJobOpeningUI : selects one job opening
EditJobOpeningUI --> CustomerManager : shows list of attributes to\nedit and asks to select one
CustomerManager -> EditJobOpeningUI : selects function attribute
EditJobOpeningUI --> CustomerManager : asks to prompt new function
CustomerManager -> EditJobOpeningUI : prompts new function
EditJobOpeningUI -> EditJobOpeningController : editFunction(JobOpening jobOpening, Designation function)
activate EditJobOpeningController
EditJobOpeningController -> JobOpening : editFunction(Designation function)
EditJobOpeningController -> JobOpeningRepository : save(JobOpening jobOpening)
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : jobOpening
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : jobOpening
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : backs to menu
deactivate EditJobOpeningUI
@enduml