@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CustomerManager
participant EditJobOpeningUI <<presentation>>
participant EditJobOpeningController <<application>>
participant JobOpeningRepository <<repository>>
participant JobOpening <<domain>>

activate CustomerManager
CustomerManager -> EditJobOpeningUI : asks to edit a job opening
activate EditJobOpeningUI
EditJobOpeningUI -> EditJobOpeningController : inactiveJobOpenings()
activate EditJobOpeningController
EditJobOpeningController -> JobOpeningRepository : findInInactiveStatus()
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : jobOpenings
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : jobOpenings
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : shows list of inactive job openings\nand asks to select one
CustomerManager -> EditJobOpeningUI : selects one
EditJobOpeningUI --> CustomerManager : shows list of attributes to\nedit and asks to select one
CustomerManager -> EditJobOpeningUI : selects address attribute
EditJobOpeningUI --> CustomerManager : asks to prompt new address
CustomerManager -> EditJobOpeningUI : prompts new address
EditJobOpeningUI -> EditJobOpeningController : edit(jobOpening, address)
activate EditJobOpeningController
EditJobOpeningController -> JobOpening : editAddress(address)
EditJobOpeningController -> JobOpeningRepository : save(jobOpening)
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController :
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI :
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : backs to menu
deactivate EditJobOpeningUI
@enduml