@startuml
'https://plantuml.com/sequence-diagram

actor CustomerManager

participant EditJobOpeningUI <<presentation>>
participant EditJobOpeningController <<application>>
participant PersistenceContext
participant RepositoryFactory
participant JobOpeningRepository <<repository>>
participant JobOpening <<domain>>

-> EditJobOpeningUI : doShow()
activate EditJobOpeningUI
EditJobOpeningUI -> EditJobOpeningController : create
EditJobOpeningUI -> EditJobOpeningController : listJobOpenings()
activate EditJobOpeningController
EditJobOpeningController -> PersistenceContext : repositories()
PersistenceContext -> RepositoryFactory : create
RepositoryFactory -> JobOpeningRepository : create
EditJobOpeningController -> JobOpeningRepository : findAll()
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : List<JobOpening>
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : List<JobOpening>
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : shows list of Job Openings\nand asks to select one
CustomerManager -> EditJobOpeningUI : selects one Job Opening
EditJobOpeningUI --> CustomerManager : show list of attributes to edit \nand asks to select one
CustomerManager -> EditJobOpeningUI : selects one attribute to edit
alt attribute is working mode
EditJobOpeningUI --> CustomerManager : asks to select new working mode
CustomerManager -> EditJobOpeningUI : selects one working mode
EditJobOpeningUI -> EditJobOpeningController : editWorkingMode(JobOpening \njobOpening, WorkingMode newWorkingMode)
activate EditJobOpeningController
EditJobOpeningController -> JobOpening : editWorkingMode(WorkingMode newWorkingMode)
end alt
alt attribute is number of vacancy
EditJobOpeningUI --> CustomerManager : asks to input new number of vacancy
CustomerManager -> EditJobOpeningUI : inputs new number of vacancy
EditJobOpeningUI -> EditJobOpeningController : editNumberVacancies(JobOpening \njobOpening, NrVacancy newNrVacancy)
EditJobOpeningController -> JobOpening : editNrVacancy(NrVacancy newNrVacancy)
end alt
alt attribute is postal address
EditJobOpeningUI -> CustomerManager : asks to input new postal address
CustomerManager -> EditJobOpeningUI : inputs new postal address
EditJobOpeningUI -> EditJobOpeningController : editPostalAddress(JobOpening jobOpening,\nPostalAddress newPostalAddress)
EditJobOpeningController -> JobOpening : editPostalAddress(PostalAddress newPostalAddress)
end alt
alt attribute is description
EditJobOpeningUI --> CustomerManager : asks to input new description
CustomerManager -> EditJobOpeningUI : input new description
EditJobOpeningUI -> EditJobOpeningController : editDescription(JobOpening \njobOpening, Description newDescription)
EditJobOpeningController -> JobOpening : editDescription(Description newDescription)
end alt
alt attribute is function
EditJobOpeningUI --> CustomerManager : asks to input new function
CustomerManager -> EditJobOpeningUI : inputs new function
EditJobOpeningUI -> EditJobOpeningController : editFunction(JobOpening \njobOpening, Designation newFunction)
EditJobOpeningController -> JobOpening : editFunction(Designation newFunction)
end alt
alt attribute is contract type
EditJobOpeningUI --> CustomerManager : asks to select new contract type
CustomerManager -> EditJobOpeningUI : selects new contract type
EditJobOpeningUI -> EditJobOpeningController : editContractType(JobOpening \nnewJobOpening, ContractType newContractType)
EditJobOpeningController -> JobOpening : editContractType(ContractType newContractType)
end alt
EditJobOpeningController -> PersistenceContext : repositories()
PersistenceContext -> RepositoryFactory : create
RepositoryFactory -> JobOpeningRepository : create
EditJobOpeningController -> JobOpeningRepository : save(JobOpening jobOpening)
activate JobOpeningRepository
JobOpeningRepository --> EditJobOpeningController : jobOpening
deactivate JobOpeningRepository
EditJobOpeningController --> EditJobOpeningUI : jobOpening
deactivate EditJobOpeningController
EditJobOpeningUI --> CustomerManager : returns to menu
deactivate EditJobOpeningUI

@enduml