@startuml
'https://plantuml.com/sequence-diagram

actor Customer  as c
participant DisplayJobOpeningUI as ui
box "Server"
participant "FollowUpServer" as server
end box
participant ListJobOpeningForCustomerController as controller
participant JobOpeningRepository as repo

autonumber

activate c
c->ui: Select the Job Application Menu
activate ui
ui->c: Displays the Job Application Menu options
deactivate ui
c->ui: Select the option to list all the Job Applications
activate ui
ui->server: Request to list all the job Openings
activate server
server->controller: getJobApplicationsForCandidate(customer)
activate controller
controller->repo: getJobOpeningsForCandidate(customer)
activate repo
repo-->controller: List<JobApplication>
deactivate repo
controller-->server: List<JobApplication>
deactivate controller
server-->ui: List<JobApplication>
deactivate server
ui->c: Displays all the Job Applications
deactivate ui
c->ui: Selects the JobApplication
activate ui
ui->c: Displays the JobApplication details

deactivate c
@enduml