@startuml





class "<<Entity>>\nCustomer" as customer{}

class "<<Entity>>\nQuestion" as question{}

class "<<Value Object>>\nQuestionType" as questiontype{}


class "<<Entity>>\nOperator" as operator {}

class "<<Entity>>\nInterviewModel" as interviewModel {}

class "<<Entity>>\nInterview" as interview {}

class "<<Entity>>\nCustomerManager" as customerManager {}


class "<<Value Object>>\nTime" as time {}

class "<<Value Object>>\nDate" as date {}

class "<<Value Object>>\nJobRequirements" as jobrequirement {}

class "<<Value Object>>\nPhases" as phases {}

package JobOpening as pkgJobOpening{
    class "<<Entity>>\nJobOpening" as jobOpening {}
    class "<<Value Object>>\nMode" as mode {}
    class "<<Value Object>>\nDuration" as duration {}
    class "<<Value Object>>\nAddress" as address {}

}

package Application as pkgApplication{
    class "<<Entity>>\nJobApplication"  as application{}
    class "<<Entity>>\nCandidate" as candidate{}
}




jobOpening -- phases
jobOpening -- mode
jobOpening -- duration
jobOpening -- address
jobOpening - jobrequirement
customer -- jobOpening
customerManager -- jobOpening
jobOpening --- interview
interview -- interviewModel
interview- date
interview- time


application -- candidate
jobOpening - application

operator---customer

interviewModel--question
question--questiontype


@enduml
