@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CustomerManager
participant GetOrderedListOfCandidatesUI <<presentation>>
participant GetOrderedListOfCandidatesController <<application>>
participant JobOpeningRepository <<repository>>
participant JobApplicationRepository <<repository>>
participant JobOpening <<domain>>
participant JobApplication <<domain>>
participant Candidate <<domain>>

activate CustomerManager
CustomerManager -> GetOrderedListOfCandidatesUI : asks to get an ordered list of\ncandidates based in interview points
activate GetOrderedListOfCandidatesUI
GetOrderedListOfCandidatesUI -> GetOrderedListOfCandidatesController : jobOpeningsInAnalysisPhaseAndHadInterviewPhase()
activate GetOrderedListOfCandidatesController
GetOrderedListOfCandidatesController -> JobOpeningRepository : findJobOpeningInAnalysisPhaseAndHadInterviewPhase()
activate JobOpeningRepository
JobOpeningRepository --> GetOrderedListOfCandidatesController : jobOpenings
deactivate JobOpeningRepository
GetOrderedListOfCandidatesController --> GetOrderedListOfCandidatesUI : jobOpenings
deactivate GetOrderedListOfCandidatesController
GetOrderedListOfCandidatesUI --> CustomerManager : shows list of job openings in \nanalysis phase and had an\ninterview phase and asks to select
CustomerManager -> GetOrderedListOfCandidatesUI : selects a job opening
GetOrderedListOfCandidatesUI -> GetOrderedListOfCandidatesController : orderCandidatesBasedOnInterviewPoints(jobOpening)
activate GetOrderedListOfCandidatesController
GetOrderedListOfCandidatesController -> JobApplicationRepository : findJobApplicationsForJobOpening(jobOpening)
activate JobApplicationRepository
JobApplicationRepository --> GetOrderedListOfCandidatesController : jobApplications
deactivate JobApplicationRepository
GetOrderedListOfCandidatesController -> JobOpening : orderCandidatesBasedOnInterviewPoints(jobApplications)
activate JobOpening
alt job opening is in analysis phase and had interview phase
JobOpening -> JobOpening : orderJobApplicationsBasedOnInterviewPoints(jobApplications)
JobOpening --> JobOpening : orderedApplications
loop for each job application
JobOpening -> JobApplication : candidate()
activate JobApplication
JobApplication -> Candidate : candidate()
activate Candidate
Candidate --> JobApplication : candidate
deactivate Candidate
JobApplication --> JobOpening : candidate
deactivate JobApplication
end loop
JobOpening --> GetOrderedListOfCandidatesController : orderedCandidates
deactivate JobOpening
GetOrderedListOfCandidatesController --> GetOrderedListOfCandidatesUI : orderedCandidates
deactivate GetOrderedListOfCandidatesController



deactivate JobApplicationRepository

GetOrderedListOfCandidatesUI --> CustomerManager : shows ordered list of candidates based\nin interview points and backs to menu
else
GetOrderedListOfCandidatesUI --> CustomerManager : shows an exception
end alt
deactivate GetOrderedListOfCandidatesUI

@enduml