@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor CustomerManager
participant System

activate CustomerManager
CustomerManager -> System : asks to edit a job opening
activate System
System --> CustomerManager : shows list of inactive job openings\nand asks to select one
CustomerManager -> System : selects one job opening
System --> CustomerManager : shows list of attributes to\nedit and asks to select one
CustomerManager -> System : selects function attribute
System --> CustomerManager : asks to prompt new function
CustomerManager -> System : prompts new function
System --> CustomerManager : backs to menu
deactivate System
@enduml